# Generated by Django 2.2.7 on 2019-11-30 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(default='00000', max_length=50, verbose_name='Senha')),
                ('status_usuario', models.CharField(choices=[('ONL', 'On-Line'), ('OFF', 'Off-Line')], default=('OFF', 'Off-Line'), max_length=3, verbose_name='Status Usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('status_funcionario', models.CharField(choices=[('E', 'Empregado'), ('DC', 'Demitido Com Justa Causa'), ('DS', 'Demitido Sem Justa Causa')], max_length=2, verbose_name='Status Funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(default='00000', max_length=50, verbose_name='Senha')),
                ('status_usuario', models.CharField(choices=[('ONL', 'On-Line'), ('OFF', 'Off-Line')], default=('OFF', 'Off-Line'), max_length=3, verbose_name='Status Usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now=True)),
                ('preco_total', models.FloatField(verbose_name='Preço total')),
                ('cod_caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Caixa')),
                ('cod_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereco')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(default='00000', max_length=50, verbose_name='Senha')),
                ('status_usuario', models.CharField(choices=[('ONL', 'On-Line'), ('OFF', 'Off-Line')], default=('OFF', 'Off-Line'), max_length=3, verbose_name='Status Usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('status_funcionario', models.CharField(choices=[('E', 'Empregado'), ('DC', 'Demitido Com Justa Causa'), ('DS', 'Demitido Sem Justa Causa')], max_length=2, verbose_name='Status Funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.FloatField(verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='ItemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco', models.FloatField(verbose_name='Preço')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('cpf_dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('preco', models.FloatField(verbose_name='Preco')),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True, verbose_name='CPF')),
                ('senha', models.CharField(default='00000', max_length=50, verbose_name='Senha')),
                ('status_usuario', models.CharField(choices=[('ONL', 'On-Line'), ('OFF', 'Off-Line')], default=('OFF', 'Off-Line'), max_length=3, verbose_name='Status Usuario')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('status_funcionario', models.CharField(choices=[('E', 'Empregado'), ('DC', 'Demitido Com Justa Causa'), ('DS', 'Demitido Sem Justa Causa')], max_length=2, verbose_name='Status Funcionario')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Gerente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrarConsulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateTimeField(verbose_name='Data da Consulta')),
                ('relatorio', models.TextField(verbose_name='Relatório')),
                ('data_retorno', models.DateField(verbose_name='Data de Retorno')),
                ('cod_pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Pet')),
                ('cod_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
                ('data_de_validade', models.DateField(verbose_name='Data de validade')),
                ('preco', models.FloatField(verbose_name='Preço')),
                ('status_produto', models.CharField(choices=[('EST', 'Estocado'), ('EXP', 'Expirado'), ('VEN', 'Vendido')], max_length=3, verbose_name='Status Produto')),
                ('cod_fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=150, verbose_name='Nome do Cliente')),
                ('nome_do_caixa', models.CharField(max_length=150, verbose_name='Nome do Caixa')),
                ('data_da_compra', models.DateTimeField(verbose_name='Data da Compra')),
                ('lista_item_produtos', models.TextField(verbose_name='Lista de Produtos')),
                ('lista_item_servicos', models.TextField(verbose_name='Lista de Serviços')),
                ('preco_total', models.FloatField(verbose_name='Preco Total')),
                ('cod_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Compra')),
            ],
        ),
        migrations.CreateModel(
            name='ListaItemServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item_servico', models.ManyToManyField(to='petshopsys_app.ItemServico')),
            ],
        ),
        migrations.CreateModel(
            name='ListaItemCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_item_compra', models.ManyToManyField(to='petshopsys_app.ItemCompra')),
            ],
        ),
        migrations.AddField(
            model_name='itemservico',
            name='cod_registrar_sevico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.RegistrarConsulta'),
        ),
        migrations.AddField(
            model_name='itemservico',
            name='cod_servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Servico'),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='cod_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Produto'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.BigIntegerField(verbose_name='Quantidade')),
                ('cod_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='compra',
            name='cod_lista_item_compra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.ListaItemCompra'),
        ),
        migrations.AddField(
            model_name='compra',
            name='cod_lista_item_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.ListaItemServico'),
        ),
        migrations.AddField(
            model_name='caixa',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petshopsys_app.Gerente'),
        ),
    ]
