# Generated by Django 2.2.7 on 2019-11-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopsys_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
