# Generated by Django 2.2.7 on 2019-11-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petshopsys_app', '0006_auto_20191126_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonecedor',
            new_name='Fornecedor',
        ),
    ]
